### PR TITLE
Update TestCases.md

### PR DESCRIPTION
**Pull request by Clementine951**
update details from the technical

### CODE REVIEW

**Review by Biohazardyee — COMMENTED** [review]
I feel like 65,535 characters would be way too much in the card, it wouldn't be possible, we need to discuss that.

**Comment by Clementine951** [comment]
This has been changed, but left with [x] instead

**Review by AlexisLasselin — APPROVED** [review]
Bettter with this change

**Review by LucasAub — APPROVED** [review]
LGTM!

**Review by Biohazardyee — APPROVED** [review]

**Review by habicll — COMMENTED** [review]
lgfm

**Comment by habicll** [comment]
lgfm

**Pull request merged**
