### PR TITLE
Create the README.md

### PR DESCRIPTION
**Pull request by AlexisLasselin**

### CODE REVIEW

**Review by Clementine951 — APPROVED** [review]
LGTM

**Review by LucasAub — CHANGES_REQUESTED** [review]
Looks good, but you can add some key features with some emojis.

**Comment by AlexisLasselin** [comment]
Maybe this commit may be good

eb72cbce0dc514eb22823939c628b770a81fdbbe

**Review by LucasAub — APPROVED** [review]
Yes exactly, looks good to me now!

**Comment by AlexisLasselin** [comment]
Thanks, 
I invite you to merge the pull request and Delete the branch

**Pull request merged**
